---
title: "Median length of stay by outcome"
output: html_notebook
---

Load the cleaned data

```{r}
outcomes_with_categories <- read.csv("intakes_outcomes_categories.csv", stringsAsFactors = F)
```

Compute length of stay

```{r}
column_names <- colnames(outcomes_with_categories)
date_columns <- column_names[grepl("Date", column_names)]
for (column in date_columns) {
  outcomes_with_categories[,column] = as.POSIXct(outcomes_with_categories[,column], format="%m/%d/%Y %H:%M:%S")
}

outcomes_with_categories[,'Length.of.Stay'] = as.numeric(outcomes_with_categories[,'Outcome.Date'] - outcomes_with_categories[,'Intake.Date'],
                                                         units='days')
```

Counts by species

```{r, rows.print=25}
species_counts <- setNames(
  aggregate(outcomes_with_categories[,"Species"], by=list(outcomes_with_categories[,"Species"]), FUN=length),
  c("Species", "Number.of.Animals"))
print(species_counts[order(-species_counts[,"Number.of.Animals"]),])
```

Filter to only dogs and cats

```{r}
dogs_and_cats <- outcomes_with_categories[outcomes_with_categories$Species %in% c('dog', 'cat'),]
```

Filter for the year 2017

```{r}
# install.packages("lubridate")
library(lubridate)
year_2017 = year(dogs_and_cats[,"Outcome.Date"]) == 2017
outcomes_2017 = dogs_and_cats[year_2017,]
print(nrow(outcomes_2017))
```

Group by category, and compute the median (and number of observations)

```{r, rows.print=30}
# install.packages("dplyr")
library(dplyr)
medians_and_counts = outcomes_2017 %>%
  group_by(Species, `Outcome.Category`) %>%
  summarise(`Median.LOS` = median(`Length.of.Stay`),
            `Number.of.Animals` = n())
print(medians_and_counts[order(medians_and_counts$Species,
                               medians_and_counts$Number.of.Animals),])
```

```{r}
write.csv(medians_and_counts[order(medians_and_counts$Species,
                               medians_and_counts$Number.of.Animals),],
          file="medians_by_species_and_category_2017.csv")
```

